import express from "express";
import path from "path";
import dotenv from "dotenv";
import { GoogleGenAI, Type } from "@google/genai";
import { createServer as createViteServer } from "vite";

// Load environment variables immediately
dotenv.config();

const app = express();
const PORT = 3000;

// Set up body parsing limits for uploading invoice images
app.use(express.json({ limit: "20mb" }));
app.use(express.urlencoded({ limit: "20mb", extended: true }));

// Initialize Google GenAI client securely on the server
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "-AQ.Ab8RN6KgadJRJIPwuv55YDoe7sKAPjMCHvHShBXabBlKhzVq4A";

const ai = new GoogleGenAI({
  apiKey: GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// ==================== BACKEND AI ENDPOINTS ====================

// 1. Health & Server Status Route
app.get("/api/health", (req, res) => {
  res.json({ status: "healthy", timestamp: new Date().toISOString() });
});

// 2. AI Copilot Chat Endpoint (With retail business grounding context)
app.post("/api/gemini/chat", async (req, res) => {
  try {
    const { message, history, context } = req.body;

    if (!message) {
      return res.status(400).json({ error: "Message is required" });
    }

    // Assemble rich context instructions for business data grounding
    let systemPrompt = `You are the Zentora AI Copilot, a brilliant and helpful retail enterprise analyst.
You help retail store merchants manage their shop operations, track inventory, analyze sales revenue/profits, manage credit ledger accounts, and optimize cash flow.
Always be professional, concise, strategic, and direct. Offer clear business actions to achieve 'Zen' retail efficiency.

Use the following real-time store data to answer the merchant's query if relevant:
${context ? JSON.stringify(context, null, 2) : "No context provided yet."}

When providing advice, format with Markdown list structures, bold text, and clean tables if appropriate. Never mention you are an AI Studio app or generated by AI. Refer to yourself only as Zentora Copilot.`;

    // Construct request contents incorporating previous context
    const contents = [];
    if (history && Array.isArray(history)) {
      for (const msg of history) {
        contents.push({
          role: msg.role === 'user' ? 'user' : 'model',
          parts: [{ text: msg.content }]
        });
      }
    }
    contents.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: contents,
      config: {
        systemInstruction: systemPrompt,
        temperature: 0.2,
      }
    });

    res.json({ text: response.text });
  } catch (err: any) {
    console.error("AI Copilot Error:", err);
    res.status(500).json({ error: err.message || "Failed to process chat with AI" });
  }
});

// 3. AI Invoice Scanner (Vision Extraction with JSON Schema)
app.post("/api/gemini/analyze-invoice", async (req, res) => {
  try {
    const { imageBase64, mimeType } = req.body;

    if (!imageBase64) {
      return res.status(400).json({ error: "Image base64 data is required" });
    }

    const imagePart = {
      inlineData: {
        mimeType: mimeType || "image/jpeg",
        data: imageBase64,
      },
    };

    const textPart = {
      text: "Analyze this supplier or retail invoice and extract the details exactly into the requested structured JSON format. Find the store name, invoice date, invoice number, list of individual products (with name, quantity, unit price, and total line item cost), and the total invoice summary price.",
    };

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: [imagePart, textPart],
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            storeName: { type: Type.STRING, description: "Extracted merchant or distributor name." },
            invoiceNumber: { type: Type.STRING, description: "The invoice ID or receipt reference number." },
            date: { type: Type.STRING, description: "Date of invoice in YYYY-MM-DD or standard readable format." },
            products: {
              type: Type.ARRAY,
              description: "List of items purchased/delivered.",
              items: {
                type: Type.OBJECT,
                properties: {
                  name: { type: Type.STRING, description: "Clean name of the product item." },
                  quantity: { type: Type.INTEGER, description: "Quantity of this item." },
                  price: { type: Type.NUMBER, description: "Unit price of this item." },
                  total: { type: Type.NUMBER, description: "Line total for this product." }
                },
                required: ["name", "quantity", "price"]
              }
            },
            total: { type: Type.NUMBER, description: "Grand total amount shown on the invoice." }
          },
          required: ["storeName", "products", "total"]
        }
      }
    });

    if (!response.text) {
      throw new Error("Empty response received from Vision extraction");
    }

    const parsedJson = JSON.parse(response.text.trim());
    res.json(parsedJson);
  } catch (err: any) {
    console.error("Invoice Scanner Error:", err);
    res.status(500).json({ error: err.message || "Failed to parse invoice using AI Vision" });
  }
});

// 4. AI Product Analyzer (Vision Analysis with JSON Schema)
app.post("/api/gemini/analyze-product", async (req, res) => {
  try {
    const { imageBase64, mimeType, nameHint } = req.body;

    if (!imageBase64) {
      return res.status(400).json({ error: "Product image base64 data is required" });
    }

    const imagePart = {
      inlineData: {
        mimeType: mimeType || "image/jpeg",
        data: imageBase64,
      },
    };

    const textPart = {
      text: `Analyze this retail product item. ${nameHint ? `The item name might be related to "${nameHint}".` : ''} Recommend the appropriate store inventory categorization, a clear product description suitable for marketing, a suggested retail price (assuming INR/USD competitive rates), and a safe stock warning threshold alert.`,
    };

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: [imagePart, textPart],
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            category: { type: Type.STRING, description: "Best retail inventory category (e.g. Beverages, Electronics, Groceries, Apparel, Personal Care)." },
            description: { type: Type.STRING, description: "Professional short commercial description for store display." },
            suggestedPrice: { type: Type.NUMBER, description: "Recommended optimal selling price." },
            minStockAlert: { type: Type.INTEGER, description: "Suggested low stock threshold warning alert limit (e.g. 5, 10, 15)." }
          },
          required: ["category", "description", "suggestedPrice", "minStockAlert"]
        }
      }
    });

    if (!response.text) {
      throw new Error("Empty response received from product analyzer");
    }

    const parsedJson = JSON.parse(response.text.trim());
    res.json(parsedJson);
  } catch (err: any) {
    console.error("Product Analyzer Error:", err);
    res.status(500).json({ error: err.message || "Failed to analyze product using AI Vision" });
  }
});

// ==================== STATIC & VITE INTEGRATION ====================

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting in DEVELOPMENT mode, mounting Vite middleware...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting in PRODUCTION mode, serving compiled assets...");
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Zentora enterprise server successfully booted at http://0.0.0.0:${PORT}`);
  });
}

startServer();
